---
- name: install apache
  become: yes
  become_method: sudo
  become_user: root
  yum:
    name: httpd
    state: latest

- name: start apache
  become: yes
  become_method: sudo
  become_user: root
  service:
    name: httpd
    state: started
    enabled: yes

