---
- name: install prerequisites
  become: yes
  become_method: sudo
  become_user: root
  yum:
    name: libsemanage-python
    state: latest

- name: install apache
  become: yes
  become_method: sudo
  become_user: root
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - httpd
    - mod_ssl

- name: start apache
  become: yes
  become_method: sudo
  become_user: root
  service:
    name: httpd
    state: started
    enabled: yes

- name: allow apache to send emails
  become: yes
  become_method: sudo
  become_user: root
  seboolean:
    name: httpd_can_sendmail
    state: yes
    persistent: yes

