---
- name: install apache and firewall
  become: yes
  become_method: sudo
  become_user: root
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - httpd
    - firewalld
    - libsemanage-python

- name: start apache and firewall
  become: yes
  become_method: sudo
  become_user: root
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - httpd
    - firewalld

- name: configure firewall
  become: yes
  become_method: sudo
  become_user: root
  firewalld:
    zone: public
    service: "{{ item }}"
    state: enabled
    permanent: yes
    immediate: yes
  with_items:
    - http
    - https

- name: allow apache to send emails
  become: yes
  become_method: sudo
  become_user: root
  seboolean:
    name: httpd_can_sendmail
    state: yes
    persistent: yes

