---
- name: install wordpress
  become: yes
  become_method: sudo
  become_user: root
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - epel-release
    - wordpress

- name: update config to allow .htaccess files
  become: yes
  become_method: sudo
  become_user: root
  replace:
    path: /etc/httpd/conf.d/wordpress.conf
    regexp: '^(\s*)AllowOverride\s+Options'
    replace: '\1AllowOverride FileInfo Options'

- name: update config to allow outside connections
  become: yes
  become_method: sudo
  become_user: root
  replace:
    path: /etc/httpd/conf.d/wordpress.conf
    regexp: '^(\s*)Require\s+local'
    replace: '\1Require all granted'

- name: update config to add virtual host definition
  become: yes
  become_method: sudo
  become_user: root
  blockinfile:
    path: /etc/httpd/conf.d/wordpress.conf
    block: |
      <VirtualHost *:80>
        ServerName www.{{ website_domain }}
        ServerAlias {{ website_domain }}
        DocumentRoot /usr/share/wordpress
      </VirtualHost>

- name: create os group to manage wordpress
  become: yes
  become_method: sudo
  become_user: root
  group:
    name: wordpress
    state: present

- name: add os user to manage wordpress
  become: yes
  become_method: sudo
  become_user: root
  user:
    name: "{{ os_user }}"
    state: present
    groups: wordpress
    append: yes

- name: add apache user to wordpress group
  become: yes
  become_method: sudo
  become_user: root
  user:
    name: apache
    groups: wordpress
    append: yes

- name: change wordpress directory ownership
  become: yes
  become_method: sudo
  become_user: root
  file:
    path: /usr/share/wordpress
    state: directory
    recurse: yes
    owner: "{{ os_user }}"
    group: wordpress

- name: change wordpress file permissions
  command: find /usr/share/wordpress -type f -exec chmod 664 {} \;

- name: change wordpress directory permissions
  command: find /usr/share/wordpress -type d -exec chmod 775 {} \;

- name: add database info to wordpress config
  become: yes
  become_method: sudo
  become_user: root
  replace:
    path: /usr/share/wordpress/wp-config.php
    regexp: "{{ item.old_text }}"
    replace: "{{ item.new_text }}"
  with_items:
    - { old_text: 'database_name_here', new_text: '{{ database.name }}' }
    - { old_text: 'username_here', new_text: '{{ database.username }}' }
    - { old_text: 'password_here', new_text: '{{ database.password }}' }

- name: change database table prefix in wordpress config
  become: yes
  become_method: sudo
  become_user: root
  replace:
    path: /usr/share/wordpress/wp-config.php
    regexp: \$table_prefix\s*=\s*'wp_'
    replace: $table_prefix = '{{ database.table_prefix }}'

- name: add .htaccess file
  template:
    src: htaccess.j2
    dest: /usr/share/wordpress/.htaccess
    owner: "{{ os_user }}"
    group: wordpress
    mode: 0644
    setype: httpd_sys_content_t

- name: restart apache
  become: yes
  become_method: sudo
  become_user: root
  service:
    name: httpd
    state: restarted

