---
- name: install certbot
  become: yes
  become_method: sudo
  become_user: root
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - epel-release
    - python-certbot-apache

- name: check for existing certificate
  stat:
    path: /etc/letsencrypt/live/{{ website_domain }}/fullchain.pem
    register: cert_file

- name: generate certificate if needed
  become: yes
  become_method: sudo
  become_user: root
  command: certbot --apache certonly -d {{ website_domain }} -d www.{{ website_domain }}
  when: cert_file.stat.exists == False

- name: set up auto certificate renewal
  become: yes
  become_method: sudo
  become_user: root
  cron:
    name: certbot cert renewal
    minute: "{{ 59 | random(seed=inventory_hostname) }}"
    hour: "*/12"
    month: "*"
    weekday: "*"
    job: "certbot renew > /var/log/certbot.log"
    state: present

